# Generated by Django 5.2.5 on 2025-09-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='product',
        ),
    ]
