# Generated by Django 5.2.5 on 2025-09-03 17:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_attribute_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
