# Generated by Django 5.2.5 on 2025-08-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_tag'),
        ('products', '0003_alter_product_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='common.tag'),
        ),
    ]
