# Generated by Django 5.2.5 on 2025-08-11 18:08

import apps.products.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to=apps.products.models.leaf_categories, on_delete=django.db.models.deletion.PROTECT, to='products.category'),
        ),
    ]
