# Generated by Django 5.2.5 on 2025-08-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_header_banner',
            field=models.BooleanField(default=False),
        ),
    ]
