# Generated by Django 5.2.5 on 2025-08-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_status_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
