# Generated by Django 5.2.5 on 2025-08-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('end_date', models.DateField()),
                ('products', models.ManyToManyField(related_name='best_deals', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
