# Generated by Django 5.2.5 on 2025-08-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_bestdeals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestdeals',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
