# Generated by Django 5.2.5 on 2025-08-15 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_category_short_identifier_product_sku_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short_identifier',
            field=models.CharField(default='ACD', max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
