# Generated by Django 5.2.5 on 2025-08-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_attribute_category_attribute_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolors',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(related_name='colors', to='products.productcolors'),
        ),
    ]
