# Generated by Django 5.2.5 on 2025-08-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productreview_review_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='feedback',
            field=models.TextField(),
        ),
    ]
