# Generated by Django 5.2.5 on 2025-09-03 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Cannot Contain Numbers.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Cannot Contain Numbers.', regex='^[A-Za-z\\s]+$')]),
        ),
    ]
