# Generated by Django 5.2.5 on 2025-08-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_category_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
