# Generated by Django 5.2.5 on 2025-08-19 16:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_delete_order'),
        ('products', '0021_productreview_review_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('np', 'Nepal')], max_length=100)),
                ('region', models.CharField(choices=[('koshi', 'Koshi'), ('madesh', 'Madesh'), ('bagmati', 'Bagmati'), ('gandaki', 'Gandaki'), ('lumbini', 'Lumbini'), ('karnali', 'Karnali'), ('sudurpaschim', 'Sudurpaschim')], max_length=100)),
                ('city', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('bhaktapur', 'Bhaktapur'), ('lalitpur', 'Lalitpur')], max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ph_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Enter a valid Nepali mobile number.', regex='^(?:\\+977[- ]?)?(?:98|97|96)\\d{8}$')])),
                ('payment_option', models.CharField(choices=[('esewa', 'Esewa'), ('cod', 'Cash on Delivery'), ('qr', 'QR')], max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_address', to='orders.address')),
                ('address_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_address', to='orders.address')),
                ('products', models.ManyToManyField(to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
