# Generated by Django 5.2.5 on 2025-08-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_seller_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
