# Generated by Django 5.2.5 on 2025-08-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_redeemed_amount_alter_order_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='multiple_sellers',
            field=models.BooleanField(default=False),
        ),
    ]
