# Generated by Django 5.2.5 on 2025-08-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_address_2_remove_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('khalti', 'Khalti'), ('qr', 'QR')], default='cod', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_region',
            field=models.CharField(choices=[('bagmati', 'Bagmati')], max_length=100),
        ),
    ]
