# Generated by Django 5.2.5 on 2025-08-31 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_sellerpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.transaction'),
        ),
    ]
