# Generated by Django 5.2.5 on 2025-08-23 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('np', 'Nepal')], default='np', max_length=100)),
                ('state', models.CharField(choices=[('bagmati', 'Bagmati')], default='bagmati', max_length=100)),
                ('city', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('bhaktapur', 'Bhaktapur'), ('lalitpur', 'Lalitpur')], default='kathmandu', max_length=100)),
                ('zip_code', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('ph_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Nepali mobile number.', regex='^(?:\\+977[- ]?)?(?:98|97|96)\\d{8}$')])),
            ],
        ),
    ]
