# Generated by Django 5.2.5 on 2025-08-22 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='ph_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Nepali mobile number.', regex='^(?:\\+977[- ]?)?(?:98|97|96)\\d{8}$')]),
        ),
    ]
