# Generated by Django 5.2.5 on 2025-09-03 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='ph_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Nepali mobile number.', regex='^(?:\\+977[- ]?)?(?:98|97|96)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
