# Generated by Django 5.2.5 on 2025-08-25 19:00

import apps.common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_addressmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            bases=(apps.common.mixins.SlugMixin, models.Model),
        ),
    ]
