# Generated by Django 5.2.5 on 2025-08-25 21:13

import apps.common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('header_text', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
            bases=(apps.common.mixins.SlugMixin, models.Model),
        ),
    ]
