# Generated by Django 5.2.5 on 2025-08-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
