# Generated by Django 5.2.5 on 2025-08-25 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_notices_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notices',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
