# Generated by Django 5.2.5 on 2025-08-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_notices_created_notices_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notices'),
        ),
    ]
