# Generated by Django 5.2.5 on 2025-09-03 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='seller_bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Cannot Contain Numbers.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='seller_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Cannot Contain Numbers.', regex='^[A-Za-z\\s]+$')]),
        ),
    ]
