# Generated by Django 5.2.5 on 2025-08-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='seller_shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='user/seller/profile/'),
        ),
    ]
