# Generated by Django 5.2.5 on 2025-08-20 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='ph_number',
            field=models.CharField(default=9800000000, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Nepali mobile number.', regex='^(?:\\+977[- ]?)?(?:98|97|96)\\d{8}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/'),
        ),
    ]
