# Generated by Django 5.2.5 on 2025-08-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authuser_ph_number_authuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='user_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], default='buyer', max_length=20),
        ),
    ]
