# Generated by Django 5.2.5 on 2025-08-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_authuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='seller_bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='seller_bank_account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='seller_bank_branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='seller_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='seller_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('seller', 'Seller')], default='user', max_length=20),
        ),
    ]
