# Generated by Django 5.2.5 on 2025-08-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_authuser_seller_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_verified_seller',
            field=models.BooleanField(default=False),
        ),
    ]
