# Generated by Django 5.2.5 on 2025-08-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='merchant_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='photos/merchant/qr_codes/'),
        ),
    ]
